In [102]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from urllib.request import urlopen#for opening urls
from bs4 import BeautifulSoup
import re#for manipulating regular expressions

In [103]:
url= "https://www.hubertiming.com/results/2018MLK"
htmlcontent=urlopen(url)

In [104]:
soup=BeautifulSoup(htmlcontent)

In [105]:
title=soup.title
title

In [106]:
title.text

'Race results for the 2018 MLK Dream Run!'

In [117]:
links=soup.find_all('a',href=True)
links

[<a href="https://www.mlkdreamrun.com/" target="_blank">MLK Dream Run</a>,
 <a href="mailto:timing@hubertiming.com">timing@hubertiming.com</a>,
 <a href="https://www.hubertiming.com">Huber Timing Home</a>,
 <a class="btn btn-primary btn-lg" href="/results/2018MLK10K" role="button" style="margin: 0px 0px 5px 5px"><i aria-hidden="true" class="fa fa-user"></i> 10K</a>,
 <a class="btn btn-primary btn-lg" href="/results/2018MLK15K" role="button" style="margin: 0px 0px 5px 5px"><i aria-hidden="true" class="fa fa-user"></i> 15K</a>,
 <a class="btn btn-primary btn-lg" href="/results/summary/2018MLK" role="button" style="margin: 0px 0px 5px 5px"><i class="fa fa-stream"></i> Summary</a>,
 <a data-url="/results/2018MLK" href="#tabs-1" id="rootTab" style="font-size: 18px">5K Results</a>,
 <a href="https://www.hubertiming.com/"><img height="65" src="https://www.hubertiming.com//sites/all/themes/hubertiming/images/clockWithFinishSign_small.png" width="50"/>Huber Timing</a>,
 <a href="https://facebook.com/hubertiming/"><img src="https://www.hubertiming.com/results/FB-f-Logo__blue_50.png"/></a>]

In [141]:
for link in links:
    print(link.get('href'))
#     similar to 
#     print(link['href'])

https://www.mlkdreamrun.com/
mailto:timing@hubertiming.com
https://www.hubertiming.com
/results/2018MLK10K
/results/2018MLK15K
/results/summary/2018MLK
#tabs-1
https://www.hubertiming.com/
https://facebook.com/hubertiming/

In [142]:
data=[]
allrows=soup.find_all('tr')
allrows

[<tr colspan="2">
 <b>5K:</b>
 </tr>,
 <tr>
 <td>Finishers:</td>
 <td>191</td>
 </tr>,
 <tr>
 <td>Male:</td>
 <td>78</td>
 </tr>,
 <tr>
 <td>Female:</td>
 <td>113</td>
 </tr>,
 <tr class="header">
 <th>Place</th>
 <th>Bib</th>
 <th>Name</th>
 <th>Gender</th>
 <th>Age</th>
 <th>City</th>
 <th>State</th>
 <th>Chip Pace</th>
 <th>Chip Time</th>
 <th>Gender Place</th>
 <th>Age Group</th>
 <th>Age Group Place</th>
 <th>Time to Start</th>
 <th>Gun Time</th>
 </tr>,
 <tr data-bib="1191">
 <td>1</td>
 <td>1191</td>
 <td>

                     MAX RANDOLPH

                 </td>
 <td>M</td>
 <td>29</td>
 <td>WASHINGTON</td>
 <td>DC</td>
 <td>5:25</td>
 <td>16:48</td>
 <td>

                     1 of 78

                 </td>
 <td>M 21-39</td>
 <td>

                     1 of 33

                 </td>
 <td>0:08</td>
 <td>16:56</td>
 </tr>,
 <tr data-bib="1080">
 <td>2</td>
 <td>1080</td>
 <td>

                     NEED NAME KAISER RUNNER

                 </td>
 <td>M</td>
 <td>25</td>
 <td>PORTLAND</td>
 <td>OR</td>
 <td>5:39</td>
 <td>17:31</td>
 <td>

                     2 of 78

                 </td>
 <td>M 21-39</td>
 <td>

                     2 of 33

                 </td>
 <td>0:09</td>
 <td>17:40</td>
 </tr>,
 <tr data-bib="1275">
 <td>3</td>
 <td>1275</td>
 <td>

                     DAN FRANEK

                 </td>
 <td>M</td>
 <td>52</td>
 <td>PORTLAND</td>
 <td>OR</td>
 <td>5:53</td>
 <td>18:15</td>
 <td>

                     3 of 78

                 </td>
 <td>M 40-54</td>
 <td>

                     1 of 27

                 </td>
 <td>0:07</td>
 <td>18:22</td>
 </tr>,
 <tr data-bib="1223">
 <td>4</td>
 <td>1223</td>
 <td>

                     PAUL TAYLOR

                 </td>
 <td>M</td>
 <td>54</td>
 <td>PORTLAND</td>
 <td>OR</td>
 <td>5:58</td>
 <td>18:31</td>
 <td>

                     4 of 78

                 </td>
 <td>M 40-54</td>
 <td>

                     2 of 27

                 </td>
 <td>0:07</td>
 <td>18:38</td>
 </tr>,
 <tr data-bib="1245">
 <td>5</td>
 <td>1245</td>
 <td>

                     THEO KINMAN

                 </td>
 <td>M</td>
 <td>22</td>
 <td></td>
 <td></td>
 <td>6:17</td>
 <td>19:31</td>
 <td>

                     5 of 78

                 </td>
 <td>M 21-39</td>
 <td>

                     3 of 33

                 </td>
 <td>0:09</td>
 <td>19:40</td>
 </tr>,
 <tr data-bib="1185">
 <td>6</td>
 <td>1185</td>
 <td>

                     MELISSA GIRGIS

                 </td>
 <td>F</td>
 <td>27</td>
 <td>PORTLAND</td>
 <td>OR</td>
 <td>6:20</td>
 <td>19:39</td>
 <td>

                     1 of 113

                 </td>
 <td>F 21-39</td>
 <td>

                     1 of 53

                 </td>
 <td>0:07</td>
 <td>19:46</td>
 </tr>,
 <tr data-bib="1251">
 <td>7</td>
 <td>1251</td>
 <td>

                     CHARLIE COGGESHALL

                 </td>
 <td>M</td>
 <td>39</td>
 <td>PORTLAND</td>
 <td>OR</td>
 <td>6:24</td>
 <td>19:51</td>
 <td>

                     6 of 78

                 </td>
 <td>M 21-39</td>
 <td>

                     4 of 33

                 </td>
 <td>0:10</td>
 <td>20:01</td>
 </tr>,
 <tr data-bib="1154">
 <td>8</td>
 <td>1154</td>
 <td>

                     UNKNOWN RUNNER SEE TIMER

                 </td>
 <td>M</td>
 <td></td>
 <td></td>
 <td></td>
 <td>8:03</td>
 <td>24:58</td>
 <td>

                     7 of 78

                 </td>
 <td></td>
 <td>

                     1 of 9

                 </td>
 <td>2:00</td>
 <td>26:58</td>
 </tr>,
 <tr data-bib="1163">
 <td>9</td>
 <td>1163</td>
 <td>

                     UNKNOWN RUNNER SEE TIMER

                 </td>
 <td>M</td>
 <td></td>
 <td></td>
 <td></td>
 <td>8:04</td>
 <td>25:01</td>
 <td>

                     8 of 78

                 </td>
 <td></td>
 <td>

                     2 of 9

                 </td>
 <td>1:59</td>
 <td>27:00</td>
 </tr>,
 <tr data-bib="1242">
 <td>10</td>
 <td>1242</td>
 <td>

                     KIMONTI WILSON

                 </td>
 <td>F</td>
 <td>48</td>
 <td></td>
 <td></td>
 <td>8:04</td>
 <td>25:01</td>
 <td>

                     2 of 113

                 </td>
 <td>F 40-54</td>
 <td>

                     1 of 37

                 </td>
 <td>1:59</td>
 <td>27:00</td>
 </tr>,
 <tr data-bib="1017">
 <td>11</td>
 <td>1017</td>
 <td>

                     COREY MCMANUS

                 </td>
 <td>M</td>
 <td>37</td>
 <td>BEAVERTON</td>
 <td>OR</td>
 <td>8:09</td>
 <td>25:17</td>
 <td>

                     9 of 78

                 </td>
 <td>M 21-39</td>
 <td>

                     5 of 33

                 </td>
 <td>0:22</td>
 <td>25:39</td>
 </tr>,
 <tr data-bib="1112">
 <td>12</td>
 <td>1112</td>
 <td>

                     MITCHELL JOHNSON

                 </td>
 <td>M</td>
 <td>25</td>
 <td>PORTLAND</td>
 <td>OR</td>
 <td>8:13</td>
 <td>25:31</td>
 <td>

                     10 of 78

                 </td>
 <td>M 21-39</td>
 <td>

                     6 of 33

                 </td>
 <td>0:15</td>
 <td>25:46</td>
 </tr>,
 <tr data-bib="1062">
 <td>13</td>
 <td>1062</td>
 <td>

                     ALEX KABA

                 </td>
 <td>M</td>
 <td>36</td>
 <td>PORTLAND</td>
 <td>OR</td>
 <td>8:14</td>
 <td>25:31</td>
 <td>

                     11 of 78

                 </td>
 <td>M 21-39</td>
 <td>

                     7 of 33

                 </td>
 <td>0:14</td>
 <td>25:45</td>
 </tr>,
 <tr data-bib="1227">
 <td>14</td>
 <td>1227</td>
 <td>

                     ROBYN MCGILLIS

                 </td>
 <td>F</td>
 <td>44</td>
 <td>PORTLAND</td>
 <td>OR</td>
 <td>8:18</td>
 <td>25:44</td>
 <td>

                     3 of 113

                 </td>
 <td>F 40-54</td>
 <td>

                     2 of 37

                 </td>
 <td>0:08</td>
 <td>25:52</td>
 </tr>,
 <tr data-bib="1067">
 <td>15</td>
 <td>1067</td>
 <td>

                     MITCHELL WARDEN

                 </td>
 <td>M</td>
 <td>29</td>
 <td>PORTLAND</td>
 <td>OR</td>
 <td>8:19</td>
 <td>25:46</td>
 <td>

                     12 of 78

                 </td>
 <td>M 21-39</td>
 <td>

                     8 of 33

                 </td>
 <td>0:14</td>
 <td>26:00</td>
 </tr>,
 <tr data-bib="1136">
 <td>16</td>
 <td>1136</td>
 <td>

                     JULIA METZ

                 </td>
 <td>F</td>
 <td>32</td>
 <td>PORTLAND</td>
 <td>OR</td>
 <td>8:33</td>
 <td>26:31</td>
 <td>

                     4 of 113

                 </td>
 <td>F 21-39</td>
 <td>

                     2 of 53

                 </td>
 <td>0:33</td>
 <td>27:04</td>
 </tr>,
 <tr data-bib="1199">
 <td>17</td>
 <td>1199</td>
 <td>

                     JEREMY AREZZINI

                 </td>
 <td>M</td>
 <td>38</td>
 <td>LAKE OSWEGO</td>
 <td>OR</td>
 <td>8:37</td>
 <td>26:44</td>
 <td>

                     13 of 78

                 </td>
 <td>M 21-39</td>
 <td>

                     9 of 33

                 </td>
 <td>0:41</td>
 <td>27:25</td>
 </tr>,
 <tr data-bib="1252">
 <td>18</td>
 <td>1252</td>
 <td>

                     ETHAN POWELL

                 </td>
 <td>M</td>
 <td></td>
 <td></td>
 <td></td>
 <td>8:40</td>
 <td>26:52</td>
 <td>

                     14 of 78

                 </td>
 <td></td>
 <td>

                     3 of 9

                 </td>
 <td>0:11</td>
 <td>27:03</td>
 </tr>,
 <tr data-bib="1231">
 <td>19</td>
 <td>1231</td>
 <td>

                     TIMOTHY KEARNEY

                 </td>
 <td>M</td>
 <td>42</td>
 <td>PORTLAND</td>
 <td>OR</td>
 <td>8:42</td>
 <td>26:58</td>
 <td>

                     15 of 78

                 </td>
 <td>M 40-54</td>
 <td>

                     3 of 27

                 </td>
 <td>0:11</td>
 <td>27:09</td>
 </tr>,
 <tr data-bib="1108">
 <td>20</td>
 <td>1108</td>
 <td>

                     TIMOTHY RINGERING

                 </td>
 <td>M</td>
 <td>50</td>
 <td>VANCOUVER</td>
 <td>WA</td>
 <td>8:43</td>
 <td>27:02</td>
 <td>

                     16 of 78

                 </td>
 <td>M 40-54</td>
 <td>

                     4 of 27

                 </td>
 <td>0:10</td>
 <td>27:12</td>
 </tr>,
 <tr data-bib="1118">
 <td>21</td>
 <td>1118</td>
 <td>

                     PONTUS JADERHOLM

                 </td>
 <td>M</td>
 <td>43</td>
 <td>PORTLAND</td>
 <td>OR</td>
 <td>8:45</td>
 <td>27:08</td>
 <td>

                     17 of 78

                 </td>
 <td>M 40-54</td>
 <td>

                     5 of 27

                 </td>
 <td>0:13</td>
 <td>27:21</td>
 </tr>,
 <tr data-bib="1246">
 <td>22</td>
 <td>1246</td>
 <td>

                     KERRY FLAGG

                 </td>
 <td>M</td>
 <td></td>
 <td></td>
 <td></td>
 <td>8:45</td>
 <td>27:10</td>
 <td>

                     18 of 78

                 </td>
 <td></td>
 <td>

                     4 of 9

                 </td>
 <td>0:10</td>
 <td>27:20</td>
 </tr>,
 <tr data-bib="1244">
 <td>23</td>
 <td>1244</td>
 <td>

                     JARRED FLAGG

                 </td>
 <td>M</td>
 <td></td>
 <td></td>
 <td></td>
 <td>8:46</td>
 <td>27:11</td>
 <td>

                     19 of 78

                 </td>
 <td></td>
 <td>

                     5 of 9

                 </td>
 <td>0:10</td>
 <td>27:21</td>
 </tr>,
 <tr data-bib="1224">
 <td>24</td>
 <td>1224</td>
 <td>

                     KEN SKEEN

                 </td>
 <td>M</td>
 <td>57</td>
 <td>PORTLAND</td>
 <td>OR</td>
 <td>8:46</td>
 <td>27:12</td>
 <td>

                     20 of 78

                 </td>
 <td>M 55+</td>
 <td>

                     1 of 5

                 </td>
 <td>0:18</td>
 <td>27:30</td>
 </tr>,
 <tr data-bib="1065">
 <td>25</td>
 <td>1065</td>
 <td>

                     SARA KOPTON

                 </td>
 <td>F</td>
 <td>40</td>
 <td>PORTLAND</td>
 <td>OR</td>
 <td>8:51</td>
 <td>27:27</td>
 <td>

                     5 of 113

                 </td>
 <td>F 40-54</td>
 <td>

                     3 of 37

                 </td>
 <td>0:20</td>
 <td>27:47</td>
 </tr>,
 <tr data-bib="1274">
 <td>26</td>
 <td>1274</td>
 <td>

                     KAISER GUEST

                 </td>
 <td>F</td>
 <td>40</td>
 <td>PORTLAND</td>
 <td>OR</td>
 <td>8:54</td>
 <td>27:37</td>
 <td>

                     6 of 113

                 </td>
 <td>F 40-54</td>
 <td>

                     4 of 37

                 </td>
 <td>0:09</td>
 <td>27:46</td>
 </tr>,
 <tr data-bib="1208">
 <td>27</td>
 <td>1208</td>
 <td>

                     JUSTIN PERZ

                 </td>
 <td>M</td>
 <td>33</td>
 <td>PORTLAND</td>
 <td>OR</td>
 <td>8:55</td>
 <td>27:39</td>
 <td>

                     21 of 78

                 </td>
 <td>M 21-39</td>
 <td>

                     10 of 33

                 </td>
 <td>0:38</td>
 <td>28:17</td>
 </tr>,
 <tr data-bib="1072">
 <td>28</td>
 <td>1072</td>
 <td>

                     ESTELA SÁNCHEZ

                 </td>
 <td>F</td>
 <td>41</td>
 <td>PORTLAND</td>
 <td>OR</td>
 <td>8:57</td>
 <td>27:45</td>
 <td>

                     7 of 113

                 </td>
 <td>F 40-54</td>
 <td>

                     5 of 37

                 </td>
 <td>0:08</td>
 <td>27:53</td>
 </tr>,
 <tr data-bib="1018">
 <td>29</td>
 <td>1018</td>
 <td>

                     JASON WILLIAMS

                 </td>
 <td>M</td>
 <td>41</td>
 <td>PORTLAND</td>
 <td>OR</td>
 <td>8:58</td>
 <td>27:50</td>
 <td>

                     22 of 78

                 </td>
 <td>M 40-54</td>
 <td>

                     6 of 27

                 </td>
 <td>0:23</td>
 <td>28:13</td>
 </tr>,
 <tr data-bib="1297">
 <td>30</td>
 <td>1297</td>
 <td>

                     ADRIANA BRITTON

                 </td>
 <td>F</td>
 <td>53</td>
 <td>PORTLAND</td>
 <td>OR</td>
 <td>9:00</td>
 <td>27:54</td>
 <td>

                     8 of 113

                 </td>
 <td>F 40-54</td>
 <td>

                     6 of 37

                 </td>
 <td>0:12</td>
 <td>28:06</td>
 </tr>,
 <tr data-bib="1117">
 <td>31</td>
 <td>1117</td>
 <td>

                     MARK WOOD

                 </td>
 <td>M</td>
 <td>43</td>
 <td>PORTLAND</td>
 <td>OR</td>
 <td>9:03</td>
 <td>28:05</td>
 <td>

                     23 of 78

                 </td>
 <td>M 40-54</td>
 <td>

                     7 of 27

                 </td>
 <td>0:30</td>
 <td>28:35</td>
 </tr>,
 <tr data-bib="1201">
 <td>32</td>
 <td>1201</td>
 <td>

                     STEVE CRANDELL

                 </td>
 <td>M</td>
 <td>61</td>
 <td>PORTLAND</td>
 <td>OR</td>
 <td>9:03</td>
 <td>28:06</td>
 <td>

                     24 of 78

                 </td>
 <td>M 55+</td>
 <td>

                     2 of 5

                 </td>
 <td>0:09</td>
 <td>28:15</td>
 </tr>,
 <tr data-bib="1110">
 <td>33</td>
 <td>1110</td>
 <td>

                     DARRELL KRIECHBAUM

                 </td>
 <td>M</td>
 <td>53</td>
 <td>PORTLAND</td>
 <td>OR</td>
 <td>9:05</td>
 <td>28:11</td>
 <td>

                     25 of 78

                 </td>
 <td>M 40-54</td>
 <td>

                     8 of 27

                 </td>
 <td>0:12</td>
 <td>28:23</td>
 </tr>,
 <tr data-bib="1104">
 <td>34</td>
 <td>1104</td>
 <td>

                     JANICE JACOBS

                 </td>
 <td>F</td>
 <td>55</td>
 <td>SALEM</td>
 <td>OR</td>
 <td>9:05</td>
 <td>28:11</td>
 <td>

                     9 of 113

                 </td>
 <td>F 55+</td>
 <td>

                     1 of 14

                 </td>
 <td>0:15</td>
 <td>28:26</td>
 </tr>,
 <tr data-bib="1300">
 <td>35</td>
 <td>1300</td>
 <td>

                     CORY ANDERSON

                 </td>
 <td>M</td>
 <td>30</td>
 <td>PORTLAND</td>
 <td>OR</td>
 <td>9:06</td>
 <td>28:14</td>
 <td>

                     26 of 78

                 </td>
 <td>M 21-39</td>
 <td>

                     11 of 33

                 </td>
 <td>0:19</td>
 <td>28:33</td>
 </tr>,
 <tr data-bib="1238">
 <td>36</td>
 <td>1238</td>
 <td>

                     PAUL SUMMERS

                 </td>
 <td>M</td>
 <td>24</td>
 <td>PORTLAND</td>
 <td>OR</td>
 <td>9:08</td>
 <td>28:21</td>
 <td>

                     27 of 78

                 </td>
 <td>M 21-39</td>
 <td>

                     12 of 33

                 </td>
 <td>0:15</td>
 <td>28:36</td>
 </tr>,
 <tr data-bib="1298">
 <td>37</td>
 <td>1298</td>
 <td>

                     ALEX NGUYEN

                 </td>
 <td>M</td>
 <td>26</td>
 <td></td>
 <td></td>
 <td>9:09</td>
 <td>28:22</td>
 <td>

                     28 of 78

                 </td>
 <td>M 21-39</td>
 <td>

                     13 of 33

                 </td>
 <td>0:19</td>
 <td>28:41</td>
 </tr>,
 <tr data-bib="1157">
 <td>38</td>
 <td>1157</td>
 <td>

                     JEREMY SWEET

                 </td>
 <td>M</td>
 <td>27</td>
 <td>PORTLAND</td>
 <td>OR</td>
 <td>9:12</td>
 <td>28:32</td>
 <td>

                     29 of 78

                 </td>
 <td>M 21-39</td>
 <td>

                     14 of 33

                 </td>
 <td>0:20</td>
 <td>28:52</td>
 </tr>,
 <tr data-bib="1106">
 <td>39</td>
 <td>1106</td>
 <td>

                     DANIEL JOHNSTON

                 </td>
 <td>M</td>
 <td>43</td>
 <td>PORTLAND</td>
 <td>OR</td>
 <td>9:12</td>
 <td>28:32</td>
 <td>

                     30 of 78

                 </td>
 <td>M 40-54</td>
 <td>

                     9 of 27

                 </td>
 <td>0:12</td>
 <td>28:44</td>
 </tr>,
 <tr data-bib="1196">
 <td>40</td>
 <td>1196</td>
 <td>

                     LIZANN DUNEGAN

                 </td>
 <td>F</td>
 <td>53</td>
 <td>PORTLAND</td>
 <td>OR</td>
 <td>9:13</td>
 <td>28:34</td>
 <td>

                     10 of 113

                 </td>
 <td>F 40-54</td>
 <td>

                     7 of 37

                 </td>
 <td>0:14</td>
 <td>28:48</td>
 </tr>,
 <tr data-bib="1239">
 <td>41</td>
 <td>1239</td>
 <td>

                     ALYX WYNN

                 </td>
 <td>F</td>
 <td>28</td>
 <td>PORTLAND</td>
 <td>OR</td>
 <td>9:14</td>
 <td>28:37</td>
 <td>

                     11 of 113

                 </td>
 <td>F 21-39</td>
 <td>

                     3 of 53

                 </td>
 <td>0:21</td>
 <td>28:58</td>
 </tr>,
 <tr data-bib="1087">
 <td>42</td>
 <td>1087</td>
 <td>

                     YALOUNDA HUNT

                 </td>
 <td>F</td>
 <td>60</td>
 <td>PORTLAND</td>
 <td>OR</td>
 <td>9:14</td>
 <td>28:40</td>
 <td>

                     12 of 113

                 </td>
 <td>F 55+</td>
 <td>

                     2 of 14

                 </td>
 <td>0:09</td>
 <td>28:49</td>
 </tr>,
 <tr data-bib="1068">
 <td>43</td>
 <td>1068</td>
 <td>

                     SERGIO RIVERA

                 </td>
 <td>M</td>
 <td>32</td>
 <td>PORTLAND</td>
 <td>OR</td>
 <td>9:15</td>
 <td>28:41</td>
 <td>

                     31 of 78

                 </td>
 <td>M 21-39</td>
 <td>

                     15 of 33

                 </td>
 <td>0:21</td>
 <td>29:02</td>
 </tr>,
 <tr data-bib="1071">
 <td>44</td>
 <td>1071</td>
 <td>

                     PEDRO FLORES

                 </td>
 <td>M</td>
 <td>42</td>
 <td>PORTLAND</td>
 <td>OR</td>
 <td>9:15</td>
 <td>28:42</td>
 <td>

                     32 of 78

                 </td>
 <td>M 40-54</td>
 <td>

                     10 of 27

                 </td>
 <td>0:08</td>
 <td>28:50</td>
 </tr>,
 <tr data-bib="1159">
 <td>45</td>
 <td>1159</td>
 <td>

                     JEFF DOWNEY

                 </td>
 <td>M</td>
 <td>36</td>
 <td>PORTLAND</td>
 <td>OR</td>
 <td>9:15</td>
 <td>28:42</td>
 <td>

                     33 of 78

                 </td>
 <td>M 21-39</td>
 <td>

                     16 of 33

                 </td>
 <td>0:19</td>
 <td>29:01</td>
 </tr>,
 <tr data-bib="1241">
 <td>46</td>
 <td>1241</td>
 <td>

                     NICK SCHUDER

                 </td>
 <td>M</td>
 <td>44</td>
 <td>PORTLAND</td>
 <td>OR</td>
 <td>9:16</td>
 <td>28:45</td>
 <td>

                     34 of 78

                 </td>
 <td>M 40-54</td>
 <td>

                     11 of 27

                 </td>
 <td>0:18</td>
 <td>29:03</td>
 </tr>,
 <tr data-bib="1023">
 <td>47</td>
 <td>1023</td>
 <td>

                     JOHN GARDNER

                 </td>
 <td>M</td>
 <td>44</td>
 <td>PORTLAND</td>
 <td>OR</td>
 <td>9:18</td>
 <td>28:51</td>
 <td>

                     35 of 78

                 </td>
 <td>M 40-54</td>
 <td>

                     12 of 27

                 </td>
 <td>0:25</td>
 <td>29:16</td>
 </tr>,
 <tr data-bib="1253">
 <td>48</td>
 <td>1253</td>
 <td>

                     JAZMIN BEMBRY

                 </td>
 <td>F</td>
 <td>23</td>
 <td>PORTLAND</td>
 <td>OR</td>
 <td>9:20</td>
 <td>28:56</td>
 <td>

                     13 of 113

                 </td>
 <td>F 21-39</td>
 <td>

                     4 of 53

                 </td>
 <td>0:15</td>
 <td>29:11</td>
 </tr>,
 <tr data-bib="1247">
 <td>49</td>
 <td>1247</td>
 <td>

                     THEO KINWAN

                 </td>
 <td>F</td>
 <td></td>
 <td></td>
 <td></td>
 <td>9:24</td>
 <td>29:09</td>
 <td>

                     14 of 113

                 </td>
 <td></td>
 <td>

                     6 of 9

                 </td>
 <td>0:10</td>
 <td>29:19</td>
 </tr>,
 <tr data-bib="1019">
 <td>50</td>
 <td>1019</td>
 <td>

                     ERIKA TURNEY

                 </td>
 <td>F</td>
 <td>46</td>
 <td>BATTLE GROUNDB</td>
 <td>WA</td>
 <td>9:24</td>
 <td>29:10</td>
 <td>

                     15 of 113

                 </td>
 <td>F 40-54</td>
 <td>

                     8 of 37

                 </td>
 <td>0:24</td>
 <td>29:34</td>
 </tr>,
 <tr data-bib="1066">
 <td>51</td>
 <td>1066</td>
 <td>

                     MICHELLE FRAZIER

                 </td>
 <td>F</td>
 <td>27</td>
 <td>PORTLAND</td>
 <td>OR</td>
 <td>9:25</td>
 <td>29:12</td>
 <td>

                     16 of 113

                 </td>
 <td>F 21-39</td>
 <td>

                     5 of 53

                 </td>
 <td>0:13</td>
 <td>29:25</td>
 </tr>,
 <tr data-bib="1151">
 <td>52</td>
 <td>1151</td>
 <td>

                     CHRISTINA LECHER

                 </td>
 <td>F</td>
 <td>31</td>
 <td>MILWAUKEE</td>
 <td>WI</td>

In [143]:
allrows[:5]

[<tr colspan="2">
 <b>5K:</b>
 </tr>,
 <tr>
 <td>Finishers:</td>
 <td>191</td>
 </tr>,
 <tr>
 <td>Male:</td>
 <td>78</td>
 </tr>,
 <tr>
 <td>Female:</td>
 <td>113</td>
 </tr>,
 <tr class="header">
 <th>Place</th>
 <th>Bib</th>
 <th>Name</th>
 <th>Gender</th>
 <th>Age</th>
 <th>City</th>
 <th>State</th>
 <th>Chip Pace</th>
 <th>Chip Time</th>
 <th>Gender Place</th>
 <th>Age Group</th>
 <th>Age Group Place</th>
 <th>Time to Start</th>
 <th>Gun Time</th>
 </tr>]

In [166]:
for row in allrows:
    rowlist=row.find_all('td')
    dataRow=[]
    for cell in rowlist:
        dataRow.append(cell.text.splitlines())      
    data.append(dataRow)
titles=data[0]
data=data[4:]

In [167]:
df=pd.DataFrame(data)
print(df)

       0       1                                                  2    3    \
0     [44]  [1071]  [                    PEDRO FLORES,            ...  [M]
1     [45]  [1159]  [                    JEFF DOWNEY,             ...  [M]
2     [46]  [1241]  [                    NICK SCHUDER,            ...  [M]
3     [47]  [1023]  [                    JOHN GARDNER,            ...  [M]
4     [48]  [1253]  [                    JAZMIN BEMBRY,           ...  [F]
...    ...     ...                                                ...  ...
2299   187    1254  \r\n\r\n                    CYNTHIA HARRIS\r\n...    F
2300   188    1085  \r\n\r\n                    EBONY LAWRENCE\r\n...    F
2301   189    1170  \r\n\r\n                    ANTHONY WILLIAMS\r...    M
2302   190    2087  \r\n\r\n                    LEESHA POSEY\r\n\r...    F
2303   191    1216  \r\n\r\n                    ZULMA OCHOA\r\n\r\...    F

       4           5     6       7        8    \
0     [42]  [PORTLAND]  [OR]  [9:15]  [28:42]
1     [36]  [PORTLAND]  [OR]  [9:15]  [28:42]
2     [44]  [PORTLAND]  [OR]  [9:16]  [28:45]
3     [44]  [PORTLAND]  [OR]  [9:18]  [28:51]
4     [23]  [PORTLAND]  [OR]  [9:20]  [28:56]
...    ...         ...   ...     ...      ...
2299    64    PORTLAND    OR   21:53  1:07:51
2300    30    PORTLAND    OR   22:00  1:08:12
2301    39    PORTLAND    OR   22:19  1:09:11
2302    43    PORTLAND    OR   30:17  1:33:53
2303    40     GRESHAM    OR   33:22  1:43:27

                                                    9    ...   254   255  \
0      [                    32 of 78,                 ]  ...  None  None
1      [                    33 of 78,                 ]  ...  None  None
2      [                    34 of 78,                 ]  ...  None  None
3      [                    35 of 78,                 ]  ...  None  None
4     [                    13 of 113,                 ]  ...  None  None
...                                                 ...  ...   ...   ...
2299  \r\n\r\n                    110 of 113\r\n\r\n...  ...  None  None
2300  \r\n\r\n                    111 of 113\r\n\r\n...  ...  None  None
2301  \r\n\r\n                    78 of 78\r\n\r\n  ...  ...  None  None
2302  \r\n\r\n                    112 of 113\r\n\r\n...  ...  None  None
2303  \r\n\r\n                    113 of 113\r\n\r\n...  ...  None  None

       256   257   258   259   260   261   262   263
0     None  None  None  None  None  None  None  None
1     None  None  None  None  None  None  None  None
2     None  None  None  None  None  None  None  None
3     None  None  None  None  None  None  None  None
4     None  None  None  None  None  None  None  None
...    ...   ...   ...   ...   ...   ...   ...   ...
2299  None  None  None  None  None  None  None  None
2300  None  None  None  None  None  None  None  None
2301  None  None  None  None  None  None  None  None
2302  None  None  None  None  None  None  None  None
2303  None  None  None  None  None  None  None  None

[2304 rows x 264 columns]

In [162]:
header_list=[]
col_headers=soup.find_all('th')
for col_header in col_headers:
    header_list.append(col_header.text)
header_list

['Place',
 'Bib',
 'Name',
 'Gender',
 'Age',
 'City',
 'State',
 'Chip Pace',
 'Chip Time',
 'Gender Place',
 'Age Group',
 'Age Group Place',
 'Time to Start',
 'Gun Time']

In [163]:
df.columns=header_list
df

ValueError: Length mismatch: Expected axis has 264 elements, new values have 14 elements

In [115]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 192 entries, 0 to 191
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Place            191 non-null    object
 1   Bib              191 non-null    object
 2   Name             191 non-null    object
 3   Gender           191 non-null    object
 4   Age              191 non-null    object
 5   City             191 non-null    object
 6   State            191 non-null    object
 7   Chip Pace        191 non-null    object
 8   Chip Time        191 non-null    object
 9   Gender Place     191 non-null    object
 10  Age Group        191 non-null    object
 11  Age Group Place  191 non-null    object
 12  Time to Start    191 non-null    object
 13  Gun Time         191 non-null    object
dtypes: object(14)
memory usage: 21.1+ KB

In [116]:
df.shape

(192, 14)

In [96]:
df2=df.dropna(axis=0,how='any')
df2.shape

(191, 14)

In [97]:
df2['ChipTimeinMinutes']=pd.to_timedelta(df2['Chip Time'])
df2['ChipTimeinMinutes']=df2['ChipTimeinMinutes'].astype('timedelta64[s]')/60
df2['ChipTimeinMinutes']

ValueError: Invalid type for timedelta scalar: <class 'list'>

In [ ]:
plt.bar(df2['Gender'],df2['ChipTimeinMinutes'])
plt.xlabel('Gender')
plt.ylabel('ChipTimeinMinutes')
plt.title("Comparison of average minutes run by females and males")

In [ ]:
df2.describe(include=[np.number])

In [ ]:
df2.boxplot(column='ChipTimeinMinutes', by='Gender')
plt.ylabel('Run time')

In [ ]:
df2['Age_i']=round(pd.to_numeric(df2['Age'], errors='coerce'))
df2.dropna(how='any',inline=True)
plt.scatter(df2['ChipTimeinMinutes'],df2['Age_i'])
plt.show()

In [ ]:
plt.scatter(df2['ChipTimeinMinutes'],df2['Age_i'])
plt.show()